### ISSUE TITLE
Hi, could you share your ModelConfig first?

### ISSUE THREAD

**Issue by Nplace-su** [georghess/NeuRAD#3]
Thanks for the excellent work! 
I'm trying to reproduce and test some methods in the paper based on nerfstuidio before the code release. I wonder if you can share your ModelConfig of nerfstudio? I can see many but not all params are in Appendix A, however, it would be of great help if you could share the config directly, thank you!

**Comment by carlinds** [comment]
Hi! Thank you for your interest in our work. We will release model configs together with the official code release. Until then, please let us know if there are any specific details you miss from the paper.

**Comment by Nplace-su** [comment]
@carlinds Thanks for your reply!
For example, I didn't find the resolutions of actor/static/proposal hashgrids, and num_levels of proposal net in the paper and appendix.

**Comment by carlinds** [comment]
For the main field the static hashgrid resolution ranges from 32 to 8192, with 8 levels, while the proposal fields use a static hashgrid resolution that ranges from 128 to 4096, with 6 levels. All fields use an actor hashgrid resolution that ranges from 64 to 1024, with 4 levels.

**Comment by Nplace-su** [comment]
@carlinds Hi, sorry to bother. May I ask how did you implement the CNN upsampler under nerfstudio frame work? I'm trying to do this, but it seems I need to do a lot of hacks to nerfstudio. So I am curious is there any more elegant way?

**Comment by georghess** [comment]
Hi! 
Adding the upsampler requires a few custom classes in nerfstudio, not sure how hacky they are. First, you’ll need a patch sampler which returns rays and the accompanying RGB patch. For the UniSim reimplementation we also have a custom pipeline to update the patch size during different stages of training. Then, in the model we’ll keep track of the expected input and output shapes to reshape them accordingly. 
If you don’t want to implement it yourself code will be released soon :)
