### ISSUE TITLE
Hyperparameter not matching

### ISSUE THREAD

**Issue by Crescent-Saturn** [georghess/NeuRAD#4]
Thanks for the excellent work!

I just found one hyperparameter was different mentioned at two place in Appendix from the paper:
1. Appendix A, Table 5, Loss weights:  
> $\lambda^{rgb} = 5.0$ 

![image](https://github.com/georghess/NeuRAD/assets/18294546/e3343af4-e813-44cb-88c4-8a5332535ade)

2. Appendix C.3, fist line: 
> "We set $\lambda_{rgb} = 1.0$"

![image](https://github.com/georghess/NeuRAD/assets/18294546/a38ea74d-20b1-4824-9263-af2cf3b6b1de)

Therefore, which one is correct? Thank you!

**Comment by georghess** [comment]
Hi @Crescent-Saturn 

Table 5 is for NeuRAD, while Section C (and hence C.3) is about our UniSim reimplementation. We tuned their hyperparameters separately, so they differ between the models.

**Comment by Crescent-Saturn** [comment]
> Hi @Crescent-Saturn
> 
> Table 5 is for NeuRAD, while Section C (and hence C.3) is about our UniSim reimplementation. We tuned their hyperparameters separately, so they differ between the models.

Thank you @georghess.
